/**
 * The words of a pre-order (lib/preorder-rules.ts), in every language a store
 * sells in: the box on the product's page, the page after paying, the
 * receipt, the email the day it comes out, and the line on the buyer's list
 * of purchases. Each day is given already written the language's way.
 * Browser-safe.
 */
import { type LanguageCode, parseLanguage } from "@/lib/store-language";

/** The space French puts before : ? ! and ;, which never breaks a line. */
const S = " ";

const en = {
  label: "Pre-order",
  button: (price: string) => `Pre-order for ${price}`,
  note: "Paid today. The day it comes out, you get it by email, at the address you pay with.",
  refund: (store: string) => `If it does not come out, ${store} refunds you in full.`,
  orWait: "Rather wait? Join the waitlist",
  expected: (day: string) => `Expected on ${day}`,
  thanksTitle: "Pre-ordered",
  thanksBought: (title: string, store: string, amount: string) => `You pre-ordered ${title} from ${store}, for ${amount}.`,
  thanksWhen: (day: string, email: string) => `It is expected on ${day}. The day it comes out, we email ${email} the way to open it.`,
  thanksWhenAddress: (day: string) => `It is expected on ${day}. The day it comes out, we email the way to open it to the address you paid with.`,
  thanksOut: "It is out now: we have emailed you the way to open it.",
  receiptSubject: (title: string) => `Your pre-order: ${title}`,
  receiptLead: (store: string) => `Thank you for your pre-order from ${store}.`,
  receiptWhat: (title: string) => `You pre-ordered: ${title}`,
  receiptPaid: (amount: string) => `Paid: ${amount}`,
  receiptRef: (reference: string) => `Order reference: ${reference}`,
  receiptWhen: (day: string) => `It is expected on ${day}. The day it comes out, we email you here the way to open it.`,
  receiptLater: "The day it comes out, we email you here the way to open it.",
  receiptRefund: (store: string) => `If it does not come out, ${store} refunds you in full. Questions? Reply to this email: it reaches ${store}.`,
  outSubject: (title: string) => `It is out: ${title}`,
  outLead: (title: string, store: string) => `${title}, which you pre-ordered from ${store}, is out, and it is yours.`,
  outOpen: "Open it here:",
  outCourse: (link: string) => `Start the course here: ${link}`,
  outQuestions: (store: string) => `Questions? Reply to this email: it reaches ${store}.`,
  ordersLine: (day: string) => `Pre-ordered. Expected on ${day}; you get it by email the day it comes out.`,
  preorderedOn: (date: string) => `Pre-ordered on ${date}`,
  notYet: "This is a pre-order. It opens the day it comes out, and you get it by email.",
};

export type PreorderWords = typeof en;

const es: PreorderWords = {
  label: "Reserva",
  button: (price) => `Resérvalo por ${price}`,
  note: "Pagas hoy. El día que salga, te llega por email, a la dirección con la que pagas.",
  refund: (store) => `Si no llega a salir, ${store} te devuelve todo el dinero.`,
  orWait: "¿Prefieres esperar? Apúntate a la lista de espera",
  expected: (day) => `Previsto para el ${day}`,
  thanksTitle: "Reservado",
  thanksBought: (title, store, amount) => `Has reservado ${title} de ${store}, por ${amount}.`,
  thanksWhen: (day, email) => `Está previsto para el ${day}. El día que salga, enviamos a ${email} cómo abrirlo.`,
  thanksWhenAddress: (day) => `Está previsto para el ${day}. El día que salga, enviamos cómo abrirlo a la dirección con la que pagaste.`,
  thanksOut: "Ya ha salido: te hemos enviado por email cómo abrirlo.",
  receiptSubject: (title) => `Tu reserva: ${title}`,
  receiptLead: (store) => `Gracias por tu reserva en ${store}.`,
  receiptWhat: (title) => `Has reservado: ${title}`,
  receiptPaid: (amount) => `Pagado: ${amount}`,
  receiptRef: (reference) => `Referencia del pedido: ${reference}`,
  receiptWhen: (day) => `Está previsto para el ${day}. El día que salga, te escribimos aquí cómo abrirlo.`,
  receiptLater: "El día que salga, te escribimos aquí cómo abrirlo.",
  receiptRefund: (store) => `Si no llega a salir, ${store} te devuelve todo el dinero. ¿Dudas? Responde a este email: le llega a ${store}.`,
  outSubject: (title) => `Ya ha salido: ${title}`,
  outLead: (title, store) => `${title}, que reservaste en ${store}, ya ha salido y es tuyo.`,
  outOpen: "Ábrelo aquí:",
  outCourse: (link) => `Empieza el curso aquí: ${link}`,
  outQuestions: (store) => `¿Dudas? Responde a este email: le llega a ${store}.`,
  ordersLine: (day) => `Reservado. Previsto para el ${day}; te llega por email el día que salga.`,
  preorderedOn: (date) => `Reservado el ${date}`,
  notYet: "Esto es una reserva. Se abre el día que salga, y te llega por email.",
};

const fr: PreorderWords = {
  label: "Précommande",
  button: (price) => `Précommander pour ${price}`,
  note: "Payé aujourd'hui. Le jour de sa sortie, vous le recevez par e-mail, à l'adresse avec laquelle vous payez.",
  refund: (store) => `S'il ne sort pas, ${store} vous rembourse intégralement.`,
  orWait: `Vous préférez attendre${S}? Inscrivez-vous sur la liste d'attente`,
  expected: (day) => `Prévu le ${day}`,
  thanksTitle: "Précommandé",
  thanksBought: (title, store, amount) => `Vous avez précommandé ${title} auprès de ${store}, pour ${amount}.`,
  thanksWhen: (day, email) => `Sa sortie est prévue le ${day}. Le jour venu, nous envoyons à ${email} de quoi l'ouvrir.`,
  thanksWhenAddress: (day) => `Sa sortie est prévue le ${day}. Le jour venu, nous envoyons de quoi l'ouvrir à l'adresse avec laquelle vous avez payé.`,
  thanksOut: `Il est sorti${S}: nous vous avons envoyé par e-mail de quoi l'ouvrir.`,
  receiptSubject: (title) => `Votre précommande${S}: ${title}`,
  receiptLead: (store) => `Merci pour votre précommande auprès de ${store}.`,
  receiptWhat: (title) => `Vous avez précommandé${S}: ${title}`,
  receiptPaid: (amount) => `Payé${S}: ${amount}`,
  receiptRef: (reference) => `Référence de la commande${S}: ${reference}`,
  receiptWhen: (day) => `Sa sortie est prévue le ${day}. Le jour venu, nous vous écrivons ici de quoi l'ouvrir.`,
  receiptLater: "Le jour de sa sortie, nous vous écrivons ici de quoi l'ouvrir.",
  receiptRefund: (store) => `S'il ne sort pas, ${store} vous rembourse intégralement. Une question${S}? Répondez à cet e-mail${S}: il arrive chez ${store}.`,
  outSubject: (title) => `C'est sorti${S}: ${title}`,
  outLead: (title, store) => `${title}, que vous avez précommandé auprès de ${store}, est sorti, et il est à vous.`,
  outOpen: `Ouvrez-le ici${S}:`,
  outCourse: (link) => `Commencez la formation ici${S}: ${link}`,
  outQuestions: (store) => `Une question${S}? Répondez à cet e-mail${S}: il arrive chez ${store}.`,
  ordersLine: (day) => `Précommandé. Prévu le ${day}${S}; vous le recevez par e-mail le jour de sa sortie.`,
  preorderedOn: (date) => `Précommandé le ${date}`,
  notYet: "Ceci est une précommande. Elle s'ouvre le jour de la sortie, et vous la recevez par e-mail.",
};

const de: PreorderWords = {
  label: "Vorbestellung",
  button: (price) => `Für ${price} vorbestellen`,
  note: "Heute bezahlt. Am Tag des Erscheinens erhalten Sie es per E-Mail, an die Adresse, mit der Sie bezahlen.",
  refund: (store) => `Erscheint es nicht, erstattet ${store} Ihnen den vollen Betrag.`,
  orWait: "Lieber warten? Tragen Sie sich in die Warteliste ein",
  expected: (day) => `Erwartet am ${day}`,
  thanksTitle: "Vorbestellt",
  thanksBought: (title, store, amount) => `Sie haben ${title} bei ${store} vorbestellt, für ${amount}.`,
  thanksWhen: (day, email) => `Es wird am ${day} erwartet. Am Tag des Erscheinens schicken wir an ${email}, wie Sie es öffnen.`,
  thanksWhenAddress: (day) => `Es wird am ${day} erwartet. Am Tag des Erscheinens schicken wir an die Adresse, mit der Sie bezahlt haben, wie Sie es öffnen.`,
  thanksOut: "Es ist jetzt erschienen: Wir haben Ihnen per E-Mail geschickt, wie Sie es öffnen.",
  receiptSubject: (title) => `Ihre Vorbestellung: ${title}`,
  receiptLead: (store) => `Danke für Ihre Vorbestellung bei ${store}.`,
  receiptWhat: (title) => `Sie haben vorbestellt: ${title}`,
  receiptPaid: (amount) => `Bezahlt: ${amount}`,
  receiptRef: (reference) => `Bestellnummer: ${reference}`,
  receiptWhen: (day) => `Es wird am ${day} erwartet. Am Tag des Erscheinens schreiben wir Ihnen hier, wie Sie es öffnen.`,
  receiptLater: "Am Tag des Erscheinens schreiben wir Ihnen hier, wie Sie es öffnen.",
  receiptRefund: (store) => `Erscheint es nicht, erstattet ${store} Ihnen den vollen Betrag. Fragen? Antworten Sie auf diese E-Mail: Sie erreicht ${store}.`,
  outSubject: (title) => `Jetzt erschienen: ${title}`,
  outLead: (title, store) => `${title}, das Sie bei ${store} vorbestellt haben, ist erschienen und gehört Ihnen.`,
  outOpen: "Hier öffnen:",
  outCourse: (link) => `Hier beginnt der Kurs: ${link}`,
  outQuestions: (store) => `Fragen? Antworten Sie auf diese E-Mail: Sie erreicht ${store}.`,
  ordersLine: (day) => `Vorbestellt. Erwartet am ${day}; Sie erhalten es am Tag des Erscheinens per E-Mail.`,
  preorderedOn: (date) => `Vorbestellt am ${date}`,
  notYet: "Das ist eine Vorbestellung. Sie öffnet sich am Tag des Erscheinens, und Sie erhalten sie per E-Mail.",
};

const it: PreorderWords = {
  label: "Preordine",
  button: (price) => `Preordina a ${price}`,
  note: "Paghi oggi. Il giorno in cui esce, lo ricevi via email, all'indirizzo con cui paghi.",
  refund: (store) => `Se non esce, ${store} ti rimborsa per intero.`,
  orWait: "Preferisci aspettare? Iscriviti alla lista d'attesa",
  expected: (day) => `Uscita prevista il ${day}`,
  thanksTitle: "Preordinato",
  thanksBought: (title, store, amount) => `Hai preordinato ${title} da ${store}, per ${amount}.`,
  thanksWhen: (day, email) => `L'uscita è prevista il ${day}. Il giorno in cui esce, inviamo a ${email} come aprirlo.`,
  thanksWhenAddress: (day) => `L'uscita è prevista il ${day}. Il giorno in cui esce, inviamo come aprirlo all'indirizzo con cui hai pagato.`,
  thanksOut: "Ora è uscito: ti abbiamo inviato via email come aprirlo.",
  receiptSubject: (title) => `Il tuo preordine: ${title}`,
  receiptLead: (store) => `Grazie per il tuo preordine da ${store}.`,
  receiptWhat: (title) => `Hai preordinato: ${title}`,
  receiptPaid: (amount) => `Pagato: ${amount}`,
  receiptRef: (reference) => `Riferimento dell'ordine: ${reference}`,
  receiptWhen: (day) => `L'uscita è prevista il ${day}. Il giorno in cui esce, ti scriviamo qui come aprirlo.`,
  receiptLater: "Il giorno in cui esce, ti scriviamo qui come aprirlo.",
  receiptRefund: (store) => `Se non esce, ${store} ti rimborsa per intero. Domande? Rispondi a questa email: arriva a ${store}.`,
  outSubject: (title) => `È uscito: ${title}`,
  outLead: (title, store) => `${title}, che hai preordinato da ${store}, è uscito ed è tuo.`,
  outOpen: "Aprilo qui:",
  outCourse: (link) => `Inizia il corso qui: ${link}`,
  outQuestions: (store) => `Domande? Rispondi a questa email: arriva a ${store}.`,
  ordersLine: (day) => `Preordinato. Uscita prevista il ${day}; lo ricevi via email il giorno in cui esce.`,
  preorderedOn: (date) => `Preordinato il ${date}`,
  notYet: "Questo è un preordine. Si apre il giorno in cui esce, e lo ricevi via email.",
};

const nl: PreorderWords = {
  label: "Voorbestellen",
  button: (price) => `Bestel vooraf voor ${price}`,
  note: "Vandaag betaald. Op de dag dat het uitkomt, krijg je het per e-mail, op het adres waarmee je betaalt.",
  refund: (store) => `Komt het niet uit, dan betaalt ${store} je alles terug.`,
  orWait: "Liever wachten? Zet je op de wachtlijst",
  expected: (day) => `Verwacht op ${day}`,
  thanksTitle: "Vooraf besteld",
  thanksBought: (title, store, amount) => `Je hebt ${title} vooraf besteld bij ${store}, voor ${amount}.`,
  thanksWhen: (day, email) => `Het wordt verwacht op ${day}. Op de dag dat het uitkomt, mailen we ${email} hoe je het opent.`,
  thanksWhenAddress: (day) => `Het wordt verwacht op ${day}. Op de dag dat het uitkomt, mailen we naar het adres waarmee je betaalde hoe je het opent.`,
  thanksOut: "Het is nu uit: we hebben je gemaild hoe je het opent.",
  receiptSubject: (title) => `Je voorbestelling: ${title}`,
  receiptLead: (store) => `Bedankt voor je voorbestelling bij ${store}.`,
  receiptWhat: (title) => `Je bestelde vooraf: ${title}`,
  receiptPaid: (amount) => `Betaald: ${amount}`,
  receiptRef: (reference) => `Bestelnummer: ${reference}`,
  receiptWhen: (day) => `Het wordt verwacht op ${day}. Op de dag dat het uitkomt, mailen we je hier hoe je het opent.`,
  receiptLater: "Op de dag dat het uitkomt, mailen we je hier hoe je het opent.",
  receiptRefund: (store) => `Komt het niet uit, dan betaalt ${store} je alles terug. Vragen? Beantwoord deze e-mail: hij komt bij ${store}.`,
  outSubject: (title) => `Het is uit: ${title}`,
  outLead: (title, store) => `${title}, dat je vooraf bestelde bij ${store}, is uit en is van jou.`,
  outOpen: "Open het hier:",
  outCourse: (link) => `Begin hier aan de cursus: ${link}`,
  outQuestions: (store) => `Vragen? Beantwoord deze e-mail: hij komt bij ${store}.`,
  ordersLine: (day) => `Vooraf besteld. Verwacht op ${day}; je krijgt het per e-mail op de dag dat het uitkomt.`,
  preorderedOn: (date) => `Vooraf besteld op ${date}`,
  notYet: "Dit is een voorbestelling. Die gaat open op de dag dat het uitkomt, en je krijgt het per e-mail.",
};

const pt: PreorderWords = {
  label: "Pré-encomenda",
  button: (price) => `Pré-encomendar por ${price}`,
  note: "Paga hoje. No dia em que sair, recebe-o por email, no endereço com que paga.",
  refund: (store) => `Se não chegar a sair, ${store} devolve-lhe o valor na totalidade.`,
  orWait: "Prefere esperar? Inscreva-se na lista de espera",
  expected: (day) => `Previsto para ${day}`,
  thanksTitle: "Pré-encomendado",
  thanksBought: (title, store, amount) => `Pré-encomendou ${title} a ${store}, por ${amount}.`,
  thanksWhen: (day, email) => `Está previsto para ${day}. No dia em que sair, enviamos para ${email} a forma de o abrir.`,
  thanksWhenAddress: (day) => `Está previsto para ${day}. No dia em que sair, enviamos a forma de o abrir para o endereço com que pagou.`,
  thanksOut: "Já saiu: enviámos-lhe por email a forma de o abrir.",
  receiptSubject: (title) => `A sua pré-encomenda: ${title}`,
  receiptLead: (store) => `Obrigado pela sua pré-encomenda a ${store}.`,
  receiptWhat: (title) => `Pré-encomendou: ${title}`,
  receiptPaid: (amount) => `Pago: ${amount}`,
  receiptRef: (reference) => `Referência da encomenda: ${reference}`,
  receiptWhen: (day) => `Está previsto para ${day}. No dia em que sair, escrevemos-lhe aqui a forma de o abrir.`,
  receiptLater: "No dia em que sair, escrevemos-lhe aqui a forma de o abrir.",
  receiptRefund: (store) => `Se não chegar a sair, ${store} devolve-lhe o valor na totalidade. Dúvidas? Responda a este email: chega a ${store}.`,
  outSubject: (title) => `Já saiu: ${title}`,
  outLead: (title, store) => `${title}, que pré-encomendou a ${store}, já saiu e é seu.`,
  outOpen: "Abra-o aqui:",
  outCourse: (link) => `Comece o curso aqui: ${link}`,
  outQuestions: (store) => `Dúvidas? Responda a este email: chega a ${store}.`,
  ordersLine: (day) => `Pré-encomendado. Previsto para ${day}; recebe-o por email no dia em que sair.`,
  preorderedOn: (date) => `Pré-encomendado a ${date}`,
  notYet: "Isto é uma pré-encomenda. Abre no dia em que sair, e recebe-a por email.",
};

export const PREORDER_WORDS: Record<LanguageCode, PreorderWords> = { en, es, fr, de, it, nl, pt };

export function preorderWords(language: unknown): PreorderWords {
  return PREORDER_WORDS[parseLanguage(language)];
}
